name: slurm-http-config
base: core20
version: '0.1'
summary: Serve slurm config over http
description: |
  Make slurm config available over http.

grade: stable
confinement: classic

apps:
  slurm-http-config:
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.8/
      LD_LIBRARY_PATH: $SNAP/usr/lib/:$SNAP/usr/lib/x86_64-linux-gnu/
    command: bin/uwsgi --processes 4 --threads 2 --http :9999 --wsgi-file $SNAP/app.py
    daemon: simple

parts:
  python:
    plugin: python
    python-packages:
      - wheel
      - uwsgi

    stage-packages:
      - libpython3.8

  slurm-http-config:
    plugin: dump
    source: src/flask/
