name: slurm-http-config
base: core20
version: '0.1'
summary: Serve slurm config over http
description: |
  Make slurm config available over http.

grade: stable
confinement: classic

apps:
  slurm-http-config:
    command: bin/uwsgi --processes 4 --threads 2 --http :9999 --wsgi-file $SNAP/app.py
    daemon: simple

parts:
  python:
    plugin: python
    python-packages:
      - uwsgi

  slurm-http-config:
    plugin: dump
    source: src/flask/
